// import match from '../dist/bundle';
// import m from './index';
// const m2 = require('../dist/bundle');
// console.log(match);
// console.log(m);
// console.log(m2);

import 'TEST/test-tmp';
import 'TEST/test-1';
import 'TEST/test-2';
import 'TEST/test-3';
import 'TEST/test-4';
import 'TEST/test-5';
import 'TEST/test-6';
import 'TEST/test-7';
import 'TEST/test-8';
import 'TEST/test-9';
import 'TEST/test-10';
import 'TEST/test-11';
import 'TEST/test-12';
import 'TEST/test-13';
